[project]
name = "university-5sem-frontend-task6"
version = "0.1.0"
description = "backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "fastapi>=0.125.0",
  "pydantic>=2.12.5",
  "python-slugify>=8.0.4",
  "sqlalchemy>=2.0.45",
  "uvicorn>=0.38.0",
]
